baseURL = "https://nsoft-america-inc.github.io/"
languageCode = "en-us"
title = "NSoft America"
theme = "PaperMod"

[params]
  description = "NSoft America Tech Blog"
  author = "NSoft America"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

