paginate = 4
baseURL = "https://nsoft-america-inc.github.io/"
languageCode = "en-us"
title = "NSoft America"
theme = "PaperMod"

[params]
  mainSections = ["posts"]
  defaultTheme = "dark"
  description = "NSoft America Tech Blog"
  author = "NSoft America"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  disableSpecial1stPost = true
  showDescription = true

  [params.profileMode]
    enabled = true
    title = "NSoft America"
    subtitle = "Innovating through Smart Factory, Logistics, and AI Solutions. We share our technical journey here."
    imageUrl = "/images/nsoft-tech-logo.png" 
    imageTitle = "NSoft America Logo"
    imageWidth = 150
    imageHeight = 150

    [[params.profileMode.buttons]]
      name = "View Posts"
      url = "/posts"
    [[params.profileMode.buttons]]
      name = "About NSoft"
      url = "https://nsoftinc.com"

 [[params.socialIcons]]
    name = "github"
    url = "https://github.com/NSoft-America-Inc"
  [[params.socialIcons]]
    name = "website"
    url = "https://nsoftinc.com"

[menu]
  [[menu.main]]
    name = "News"
    identifier = "news-category"
    url = "/categories/news/"
    weight = 10
  [[menu.main]]
    name = "Tech"
    identifier = "tech-category"
    url = "/categories/tech/"
    weight = 20
  [[menu.main]]
    name = "Cloud"
    identifier = "cloud-category"
    url = "/categories/cloud/"
    weight = 25
  [[menu.main]]
    name = "All Posts"
    identifier = "all-posts"
    url = "/posts/"
    weight = 30
  [[menu.main]]
    name = "About"
    identifier = "about-page"
    url = "/about/"
    weight = 40

[permalinks]
  posts = "/posts/:contentbasename/"
  cloud = "/posts/:contentbasename/"
  tech = "/posts/:contentbasename/"
  news = "/posts/:contentbasename/"
  guide = "/posts/:contentbasename/"

